default:
	clear
	scalac -d out -classpath ./out/:../../../lib/json-smart-1.1.1.jar src/JSONScala.scala
	scalac -d out -classpath ./out/ src/ShortestPath.scala
fast:
	clear
	fsc -d out -classpath ./out/:../../../lib/json-smart-1.1.1.jar src/JSONScala.scala
	fsc -d out -classpath ./out/ src/ShortestPath.scala
