default:
	clear
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/Ticket.scala
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/Route.scala
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/Messages.scala
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/BookingManager.scala
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/PathResolver.scala
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/SynchRequestsHandler.scala
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/RequestReceiver.scala
	scalac -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/TicketOffice.scala
fast: 
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/Ticket.scala
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/Route.scala
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/Messages.scala
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/BookingManager.scala
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/PathResolver.scala
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/SynchRequestsHandler.scala
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/RequestReceiver.scala
	fsc -d out -unchecked  -classpath ./out/:../lib/yami4.jar:../lib/json-smart-1.1.1.jar src/TicketOffice.scala
clean:
	rm -f out/*.class
