GNAT=gnatmake
FLAGS=-P
PROJECT_ADDRESS=
PROJECT_NAME=railway_project

default:
	clear
	$(GNAT) $(FLAGS) $(PROJECT_ADDRESS)$(PROJECT_NAME)
	#$(GNAT) $(FLAGS) server
clean:
	rm -rf out/*
	rm -rf railway_project
	clear
